version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: space
      POSTGRES_PASSWORD: trouble
    ports:
      - "5432"

  space-trouble:
    build:
      context: .
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - "postgres"
    environment:
      POSTGRESQL_URL: "postgresql://space:trouble@postgres:5432?sslmode=disable"
