// Code generated by mockery v2.14.0. DO NOT EDIT.

package entrypoints

import (
	context "context"

	types "github.com/leveldorado/space-trouble/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// mockOrdersService is an autogenerated mock type for the ordersService type
type mockOrdersService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, o
func (_m *mockOrdersService) Create(ctx context.Context, o types.Order) (string, error) {
	ret := _m.Called(ctx, o)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, types.Order) string); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, types.Order) error); ok {
		r1 = rf(ctx, o)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *mockOrdersService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Destinations provides a mock function with given fields: ctx
func (_m *mockOrdersService) Destinations(ctx context.Context) ([]types.Destination, error) {
	ret := _m.Called(ctx)

	var r0 []types.Destination
	if rf, ok := ret.Get(0).(func(context.Context) []types.Destination); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Destination)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, id
func (_m *mockOrdersService) Get(ctx context.Context, id string) (types.Order, error) {
	ret := _m.Called(ctx, id)

	var r0 types.Order
	if rf, ok := ret.Get(0).(func(context.Context, string) types.Order); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(types.Order)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *mockOrdersService) List(ctx context.Context, limit int, offset int) ([]types.Order, error) {
	ret := _m.Called(ctx, limit, offset)

	var r0 []types.Order
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []types.Order); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewMockOrdersService interface {
	mock.TestingT
	Cleanup(func())
}

// newMockOrdersService creates a new instance of mockOrdersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockOrdersService(t mockConstructorTestingTnewMockOrdersService) *mockOrdersService {
	mock := &mockOrdersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
