// Code generated by mockery v2.14.0. DO NOT EDIT.

package services

import (
	context "context"

	types "github.com/leveldorado/space-trouble/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// mockLaunchpadRepo is an autogenerated mock type for the launchpadRepo type
type mockLaunchpadRepo struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, id
func (_m *mockLaunchpadRepo) Get(ctx context.Context, id string) (types.Launchpad, error) {
	ret := _m.Called(ctx, id)

	var r0 types.Launchpad
	if rf, ok := ret.Get(0).(func(context.Context, string) types.Launchpad); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(types.Launchpad)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewMockLaunchpadRepo interface {
	mock.TestingT
	Cleanup(func())
}

// newMockLaunchpadRepo creates a new instance of mockLaunchpadRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockLaunchpadRepo(t mockConstructorTestingTnewMockLaunchpadRepo) *mockLaunchpadRepo {
	mock := &mockLaunchpadRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
