// Code generated by mockery v2.14.0. DO NOT EDIT.

package services

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	types "github.com/leveldorado/space-trouble/pkg/types"
)

// mockCompetitorLaunchesRepo is an autogenerated mock type for the competitorLaunchesRepo type
type mockCompetitorLaunchesRepo struct {
	mock.Mock
}

// ListByDate provides a mock function with given fields: ctx, launchpad, date
func (_m *mockCompetitorLaunchesRepo) ListByDate(ctx context.Context, launchpad string, date time.Time) ([]types.Launch, error) {
	ret := _m.Called(ctx, launchpad, date)

	var r0 []types.Launch
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []types.Launch); ok {
		r0 = rf(ctx, launchpad, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Launch)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, launchpad, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewMockCompetitorLaunchesRepo interface {
	mock.TestingT
	Cleanup(func())
}

// newMockCompetitorLaunchesRepo creates a new instance of mockCompetitorLaunchesRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockCompetitorLaunchesRepo(t mockConstructorTestingTnewMockCompetitorLaunchesRepo) *mockCompetitorLaunchesRepo {
	mock := &mockCompetitorLaunchesRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
